import type { GameModule } from '../../core/game-types';
import { makeFrame, xy } from '../_shared/game-ui';

const WORDS = ['MINT', 'NOVA', 'TRAIL', 'PLAY', 'GLOW'];
const GRID = ['MINTQZLP', 'ANOVAWRE', 'TRAILKAY', 'PGLowZNE'.toUpperCase(), 'EYXQZVOR', 'BPLAYSUN', 'CDHEARTS', 'FROSTICE'].map(row => row.split(''));
type Cell = [number, number];
export const game: GameModule = {
  meta: { slug: 'word-grid', title: 'Word Trail', category: 'puzzle', description: 'Trace hidden words through a glowing letter trail.', instructions: 'Drag through adjacent letters to spell every word.', accent: '#B18CFF', mechanic: 'Connect adjacent letters' },
  mount(host, services) {
    const frame = makeFrame(host, '#B18CFF', 'Word Trail'); const { ctx, canvas } = frame; const N = 8, S = 63, O = 48; let path: Cell[] = [], found: string[] = [], dragging = false, paused = false, cursor: Cell = [0, 0];
    const key = ([x, y]: Cell) => `${x},${y}`; const word = () => path.map(([x, y]) => GRID[y][x]).join('');
    const draw = () => { ctx.fillStyle = '#101128'; ctx.fillRect(0, 0, 600, 600); found.forEach((_, i) => { ctx.fillStyle = ['#70F0C2','#FFDA74','#FF8195','#59C9FF','#B18CFF'][i]; ctx.fillRect(30 + i * 108, 18, 96, 5); }); path.forEach(([x, y], i) => { if (!i) return; const [px, py] = path[i - 1]; ctx.strokeStyle = '#B18CFF'; ctx.lineWidth = 10; ctx.lineCap = 'round'; ctx.beginPath(); ctx.moveTo(O + px * S + 28, 105 + py * S + 28); ctx.lineTo(O + x * S + 28, 105 + y * S + 28); ctx.stroke(); }); for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const inPath = path.some(p => p[0] === x && p[1] === y); ctx.fillStyle = inPath ? '#4C3B86' : '#202342'; ctx.beginPath(); ctx.arc(O + x * S + 28, 105 + y * S + 28, 25, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = x === cursor[0] && y === cursor[1] ? '#70F0C2' : 'transparent'; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = '#F7F9FF'; ctx.font = '700 22px system-ui'; ctx.textAlign = 'center'; ctx.fillText(GRID[y][x], O + x * S + 28, 113 + y * S + 28); } ctx.textAlign = 'start'; ctx.fillStyle = '#A8B1C5'; ctx.font = '700 15px system-ui'; ctx.fillText(WORDS.filter(w => !found.includes(w)).join('  ·  ') || 'ALL TRAILS FOUND', 45, 572); frame.setHud(`FOUND ${found.length}/${WORDS.length} · ${word() || 'TRACE A WORD'}`); };
    const cellAt = (e: PointerEvent) => { const p = xy(canvas, e); const x = Math.floor((p.x - O) / S), y = Math.floor((p.y - 105) / S); return x >= 0 && x < N && y >= 0 && y < N ? [x, y] as Cell : null; };
    const extend = (cell: Cell | null) => { if (!cell || paused) return; const last = path.at(-1); if (last && key(last) === key(cell)) return; if (!last || (Math.abs(last[0] - cell[0]) <= 1 && Math.abs(last[1] - cell[1]) <= 1 && !path.some(p => key(p) === key(cell)))) { path.push(cell); services.sound.play('move'); draw(); } };
    const finish = () => { const text = word(); if (WORDS.includes(text) && !found.includes(text)) { found.push(text); services.sound.play('success'); services.reportScore(found.length * 100); if (found.length > services.storage.get<number>('word-grid-best', 0)) services.storage.set('word-grid-best', found.length); if (found.length === WORDS.length) { services.reportComplete(1); frame.setMessage('Every trail is lit!'); } } else if (path.length > 1) services.sound.play('tap'); path = []; draw(); };
    const reset = () => { path = []; found = []; frame.setMessage('Find five trails in any direction.'); draw(); };
    frame.on(canvas, 'pointerdown', ((e: PointerEvent) => { dragging = true; path = []; extend(cellAt(e)); canvas.setPointerCapture(e.pointerId); }) as EventListener); frame.on(canvas, 'pointermove', ((e: PointerEvent) => { if (dragging) extend(cellAt(e)); }) as EventListener); frame.on(canvas, 'pointerup', (() => { if (dragging) finish(); dragging = false; }) as EventListener); frame.on(frame.root, 'keydown', ((e: KeyboardEvent) => { if (e.key === 'ArrowLeft') cursor[0] = Math.max(0, cursor[0] - 1); if (e.key === 'ArrowRight') cursor[0] = Math.min(7, cursor[0] + 1); if (e.key === 'ArrowUp') cursor[1] = Math.max(0, cursor[1] - 1); if (e.key === 'ArrowDown') cursor[1] = Math.min(7, cursor[1] + 1); if (e.key === ' ') extend(cursor); if (e.key === 'Enter') finish(); if (e.key.toLowerCase() === 'r') reset(); draw(); }) as EventListener);
    reset(); return { pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => frame.destroy() };
  },
};
export default game;
