import type { GameModule } from '../../core/game-types';
import { keyPrevent, makeFrame, rr, xy } from '../_shared/game-ui';

type Cell = { mine: boolean; open: boolean; flag: boolean; near: number };
export const game: GameModule = {
  meta: { slug: 'mines', title: 'Pocket Mines', category: 'puzzle', description: 'A compact field of risky crystals.', instructions: 'Tap to reveal. Hold a cell or right-click to plant a flag.', accent: '#FF6B7A', mechanic: 'Reveal, flag, deduce' },
  mount(host, services) {
    const frame = makeFrame(host, '#FF6B7A', 'Pocket Mines'); const { ctx, canvas } = frame; const N = 9, SIZE = 60, mines = 10; let cells: Cell[][], active = true, paused = false, revealed = 0, flags = 0, held: number | undefined, cursor: [number, number] = [0, 0];
    const setup = () => { cells = Array.from({ length: N }, () => Array.from({ length: N }, () => ({ mine: false, open: false, flag: false, near: 0 }))); let placed = 0; while (placed < mines) { const x = rr(services, N), y = rr(services, N); if (!cells[y][x].mine) { cells[y][x].mine = true; placed++; } } cells.forEach((row, y) => row.forEach((cell, x) => cell.near = [-1, 0, 1].flatMap(dy => [-1, 0, 1].map(dx => [x + dx, y + dy])).filter(([nx, ny]) => nx >= 0 && nx < N && ny >= 0 && ny < N && cells[ny][nx].mine).length)); active = true; revealed = flags = 0; cursor = [0, 0]; frame.setMessage('Find all safe tiles.'); draw(); };
    const draw = () => { ctx.fillStyle = '#0B1020'; ctx.fillRect(0, 0, 600, 600); cells.forEach((row, y) => row.forEach((cell, x) => { const px = 30 + x * SIZE, py = 30 + y * SIZE; ctx.fillStyle = cell.open ? '#222A42' : '#31405D'; ctx.fillRect(px + 2, py + 2, 54, 54); ctx.strokeStyle = '#5b6882'; ctx.strokeRect(px + 2, py + 2, 54, 54); if (cell.flag) { ctx.fillStyle = '#FF6B7A'; ctx.beginPath(); ctx.moveTo(px + 21, py + 15); ctx.lineTo(px + 40, py + 23); ctx.lineTo(px + 21, py + 31); ctx.fill(); ctx.fillRect(px + 20, py + 15, 3, 29); } else if (cell.open && cell.mine) { ctx.fillStyle = '#FF6B7A'; ctx.beginPath(); ctx.arc(px + 29, py + 29, 13, 0, Math.PI * 2); ctx.fill(); } else if (cell.open && cell.near) { ctx.fillStyle = ['','#70F0C2','#59C9FF','#FFDA74','#FF8195','#B18CFF'][cell.near] || '#F7F9FF'; ctx.font = '800 25px system-ui'; ctx.textAlign = 'center'; ctx.fillText(String(cell.near), px + 29, py + 38); ctx.textAlign = 'start'; } })); ctx.strokeStyle = '#70F0C2'; ctx.lineWidth = 3; ctx.strokeRect(32 + cursor[0] * SIZE, 32 + cursor[1] * SIZE, 50, 50); frame.setHud(`SAFE ${revealed}/${N * N - mines} · FLAGS ${flags}/${mines}`); };
    const flood = (x: number, y: number) => { const cell = cells[y]?.[x]; if (!cell || cell.open || cell.flag) return; cell.open = true; revealed++; if (!cell.near) for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) if (dx || dy) flood(x + dx, y + dy); };
    const reveal = (x: number, y: number) => { if (!active || paused) return; const c = cells[y]?.[x]; if (!c || c.flag || c.open) return; if (c.mine) { c.open = true; active = false; cells.flat().filter(cell => cell.mine).forEach(cell => cell.open = true); services.sound.play('fail'); frame.setMessage('Crystal burst. Press R for a fresh field.'); draw(); return; } flood(x, y); services.reportScore(revealed); if (revealed > services.storage.get<number>('mines-best', 0)) services.storage.set('mines-best', revealed); services.sound.play('tap'); if (revealed === N * N - mines) { active = false; services.sound.play('success'); services.reportComplete(1); frame.setMessage('Field secured! Press R to play again.'); } draw(); };
    const flag = (x: number, y: number) => { const c = cells[y]?.[x]; if (!active || !c || c.open) return; c.flag = !c.flag; flags += c.flag ? 1 : -1; services.sound.play('tap'); draw(); };
    const point = (event: PointerEvent) => { const p = xy(canvas, event); return { x: Math.floor((p.x - 30) / SIZE), y: Math.floor((p.y - 30) / SIZE) }; };
    frame.on(canvas, 'contextmenu', ((e: MouseEvent) => { e.preventDefault(); const p = xy(canvas, e as unknown as PointerEvent); flag(Math.floor((p.x - 30) / SIZE), Math.floor((p.y - 30) / SIZE)); }) as EventListener);
    frame.on(canvas, 'pointerdown', ((e: PointerEvent) => { if (paused) return; const p = point(e); held = window.setTimeout(() => { if (!paused) flag(p.x, p.y); held = undefined; }, 520); }) as EventListener);
    frame.on(canvas, 'pointerup', ((e: PointerEvent) => { if (held !== undefined) { clearTimeout(held); held = undefined; const p = point(e); reveal(p.x, p.y); } }) as EventListener);
    frame.on(frame.root, 'keydown', ((e: KeyboardEvent) => { keyPrevent(e, ['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' ','f','F','r','R']); if (e.key === 'ArrowUp') cursor[1] = Math.max(0, cursor[1] - 1); if (e.key === 'ArrowDown') cursor[1] = Math.min(N - 1, cursor[1] + 1); if (e.key === 'ArrowLeft') cursor[0] = Math.max(0, cursor[0] - 1); if (e.key === 'ArrowRight') cursor[0] = Math.min(N - 1, cursor[0] + 1); if (e.key === 'Enter' || e.key === ' ') reveal(...cursor); if (e.key.toLowerCase() === 'f') flag(...cursor); if (e.key.toLowerCase() === 'r') setup(); draw(); }) as EventListener);
    setup(); return { pause: () => { paused = true; if (held !== undefined) { clearTimeout(held); held = undefined; } }, resume: () => { paused = false; }, restart: setup, destroy: () => { if (held !== undefined) clearTimeout(held); frame.destroy(); } };
  },
};
export default game;
