import type { GameController, GameModule, GameServices } from '../../core/game-types';
import { clamp, makeKit, text } from '../arcade-kit';

type Hazard = { lane: number; y: number; kind: number };

export const runner: GameModule = { meta: { slug: 'runner', title: 'Metro Dash', category: 'action', description: 'Sprint the glowing rails as traffic closes in.', instructions: 'Swipe lanes, swipe up to jump, down to slide; arrows also work.', accent: '#ffcb6b', mechanic: 'Switch lanes, jump, duck' }, mount(host: HTMLElement, services: GameServices): GameController {
  const k = makeKit(host, services, 'runner'); let raf = 0, paused = false, over = false, score = 0, lane = 1, y = 0, vy = 0, duck = 0, time = 0, moveLock = 0, start: { x: number; y: number } | null = null, objects: Hazard[] = [];
  const reset = () => { paused = false; over = false; score = 0; lane = 1; y = 0; vy = 0; duck = 0; time = 0; moveLock = 0; objects = []; }; const jump = () => { if (!y) { vy = 10; services.sound.play('jump'); } }; const duckAction = () => { if (!duck) services.sound.play('move'); duck = 34; }; const shift = (amount: number) => { const next = clamp(lane + amount, 0, 2); if (next !== lane) { lane = next; services.sound.play('move'); } };
  reset(); k.on('pointerdown', event => { start = k.point(event as PointerEvent); }); k.on('pointerup', event => { if (over) { reset(); return; } if (!start) return; const point = k.point(event as PointerEvent), dx = point.x - start.x, dy = point.y - start.y; if (Math.abs(dx) > Math.abs(dy)) shift(dx > 0 ? 1 : -1); else if (dy < -18) jump(); else if (dy > 18) duckAction(); start = null; }); k.on('keydown', event => { const key = (event as KeyboardEvent).key; if (over && (key === ' ' || key === 'Enter')) reset(); if (key === 'ArrowUp' || key === 'w' || key === ' ') jump(); if (key === 'ArrowDown' || key === 's') duckAction(); if (key === 'ArrowLeft' || key === 'a') shift(-1); if (key === 'ArrowRight' || key === 'd') shift(1); });
  const draw = () => { const c = k.ctx; k.clear(); c.fillStyle = '#11132a'; c.fillRect(0, 0, 360, 560); for (let index = 0; index < 3; index++) { c.fillStyle = index === lane ? '#243755' : '#182239'; c.fillRect(45 + index * 90, 45, 70, 470); c.fillStyle = '#384968'; c.fillRect(77 + index * 90, 45, 5, 470); } text(c, `DISTANCE ${score}m`, 180, 28, 15, '#a8b1c5'); objects.forEach(object => { const x = 62 + object.lane * 90; c.fillStyle = object.kind ? '#ff6b7a' : '#8b7cff'; if (object.kind) c.fillRect(x, object.y, 55, 45); else { c.beginPath(); c.arc(x + 28, object.y + 25, 24, 0, 7); c.fill(); } }); const playerX = 65 + lane * 90; c.fillStyle = '#70f0c2'; c.fillRect(playerX, 460 - y + (duck ? 20 : 0), 40, duck ? 20 : 52); c.fillStyle = '#f7f9ff'; c.fillRect(playerX + 7, 468 - y + (duck ? 20 : 0), 7, 7); if (paused) text(c, 'PAUSED', 180, 280, 27); if (over) { text(c, 'TRAIN CAUGHT YOU', 180, 245, 24, '#ff6b7a'); text(c, 'Tap to run again', 180, 278, 15); } };
  const loop = () => { if (!paused && !over) { time++; score = Math.floor(time / 6); const spawnEvery = Math.max(30, 85 - score / 14); if (time % spawnEvery < 1) objects.push({ lane: Math.floor(services.random() * 3), y: 45, kind: services.random() > .55 ? 1 : 0 }); moveLock--; if (moveLock <= 0) { if (k.keys.has('ArrowLeft') || k.keys.has('a')) { shift(-1); moveLock = 9; } if (k.keys.has('ArrowRight') || k.keys.has('d')) { shift(1); moveLock = 9; } } if (k.keys.has('ArrowUp') || k.keys.has('w')) jump(); if (k.keys.has('ArrowDown') || k.keys.has('s')) duckAction(); y += vy; vy -= .65; if (y < 0) { y = 0; vy = 0; } if (duck) duck--; objects.forEach(object => { object.y += 5 + score / 100; }); for (const object of objects) if (object.lane === lane && object.y > 430 && object.y < 510 && !(object.kind === 0 && y > 38) && !(object.kind === 1 && duck)) { over = true; services.sound.play('fail'); k.score(score); } objects = objects.filter(object => object.y < 570); if (score && score % 250 === 0 && time % 6 === 0) { services.reportComplete(Math.floor(score / 250)); services.sound.play('upgrade'); } } draw(); raf = requestAnimationFrame(loop); };
  loop(); return { pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => { cancelAnimationFrame(raf); k.dispose(); } };
} };
export default runner;
