import type { GameController, GameModule, GameServices } from '../../core/game-types';
import { clamp, makeKit, text } from '../arcade-kit';

const palette = ['#70f0c2', '#8b7cff', '#ffcb6b', '#ff6b7a'];
type Bubble = { x: number; y: number; color: number };

export const bubble: GameModule = {
  meta: { slug: 'bubble', title: 'Bubble Pop', category: 'puzzle', description: 'Aim charged bubbles into matching clusters.', instructions: 'Drag from the launcher and release to shoot; arrows and Space also work.', accent: '#70f0c2', mechanic: 'Match colored bubbles' },
  mount(host: HTMLElement, services: GameServices): GameController {
    const k = makeKit(host, services, 'bubble'); let raf = 0, paused = false, score = 0, level = 1, over = false, next = 0, aim = { x: 180, y: 140 };
    let flying: { x: number; y: number; dx: number; dy: number; color: number } | null = null, field: Bubble[] = [];
    const reset = () => { paused = false; score = 0; level = 1; over = false; next = 0; flying = null; field = []; for (let r = 0; r < 5; r++) for (let col = 0; col < 8; col++) field.push({ x: 27 + col * 43 + (r % 2) * 20, y: 55 + r * 37, color: Math.floor(services.random() * 4) }); };
    const shoot = () => { if (paused || over || flying) return; const dx = aim.x - 180, dy = aim.y - 510, length = Math.hypot(dx, dy) || 1; flying = { x: 180, y: 510, dx: dx / length * (7 + level * .25), dy: dy / length * (7 + level * .25), color: next }; next = Math.floor(services.random() * 4); services.sound.play('shoot'); };
    k.on('pointermove', event => { aim = k.point(event as PointerEvent); }); k.on('pointerup', shoot); k.on('pointerdown', event => { if (over) reset(); else aim = k.point(event as PointerEvent); });
    k.on('keydown', event => { const key = (event as KeyboardEvent).key; if (over && (key === ' ' || key === 'Enter' || key === 'r')) { reset(); return; } if (key === 'ArrowLeft' || key === 'a') aim.x = clamp(aim.x - 18, 15, 345); if (key === 'ArrowRight' || key === 'd') aim.x = clamp(aim.x + 18, 15, 345); if (key === 'ArrowUp' || key === 'w') aim.y = clamp(aim.y - 18, 45, 440); if (key === 'ArrowDown' || key === 's') aim.y = clamp(aim.y + 18, 45, 440); if (key === ' ' || key === 'Enter') shoot(); });
    const attach = (shot: NonNullable<typeof flying>) => { flying = null; const near = field.reduce((best, item) => Math.hypot(shot.x - item.x, shot.y - item.y) < Math.hypot(shot.x - best.x, shot.y - best.y) ? item : best, field[0]); if (near) { const d = Math.hypot(shot.x - near.x, shot.y - near.y) || 1; shot.x = near.x + (shot.x - near.x) / d * 36; shot.y = near.y + (shot.y - near.y) / d * 36; } else shot.y = 55; const placed: Bubble = { x: clamp(shot.x, 20, 340), y: Math.max(52, shot.y), color: shot.color }; field.push(placed); services.sound.play('hit'); const group: Bubble[] = []; const visit = (item: Bubble) => { if (group.includes(item)) return; group.push(item); field.filter(other => other.color === item.color && Math.hypot(other.x - item.x, other.y - item.y) < 43).forEach(visit); }; visit(placed); if (group.length >= 3) { field = field.filter(item => !group.includes(item)); score += group.length * 10; k.score(score); services.sound.play('clear'); if (!field.length) { level++; services.reportComplete(level); services.sound.play('upgrade'); for (let r = 0; r < Math.min(7, 4 + level); r++) for (let col = 0; col < 8; col++) field.push({ x: 27 + col * 43 + (r % 2) * 20, y: 55 + r * 37, color: Math.floor(services.random() * 4) }); } } };
    const draw = () => { const c = k.ctx; k.clear(); c.fillStyle = '#12192a'; c.fillRect(0, 0, 360, 560); text(c, `POP ${score}  ·  LEVEL ${level}`, 180, 27, 14, '#a8b1c5'); c.strokeStyle = '#273149'; c.setLineDash([6, 6]); c.beginPath(); c.moveTo(180, 510); c.lineTo(aim.x, aim.y); c.stroke(); c.setLineDash([]); field.forEach(item => { c.fillStyle = palette[item.color]; c.beginPath(); c.arc(item.x, item.y, 18, 0, 7); c.fill(); }); if (flying) { c.fillStyle = palette[flying.color]; c.beginPath(); c.arc(flying.x, flying.y, 18, 0, 7); c.fill(); } c.fillStyle = palette[next]; c.beginPath(); c.arc(180, 510, 18, 0, 7); c.fill(); if (paused) text(c, 'PAUSED', 180, 280, 27); if (over) { text(c, 'BUBBLES DESCENDED', 180, 270, 22, '#ff6b7a'); text(c, 'Tap or Space to retry', 180, 300, 15); } };
    const loop = () => { if (!paused && !over && flying) { flying.x += flying.dx; flying.y += flying.dy; if (flying.x < 18 || flying.x > 342) flying.dx *= -1; if (flying.y < 52 || field.some(item => Math.hypot(item.x - flying!.x, item.y - flying!.y) < 35)) attach(flying); } if (!over && field.some(item => item.y > 485)) { over = true; services.sound.play('fail'); } draw(); raf = requestAnimationFrame(loop); };
    reset(); loop(); return { pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => { cancelAnimationFrame(raf); k.dispose(); } };
  }
};
export default bubble;
