import type { GameModule } from '../../core/game-types';
import { clamp, makeFrame } from '../_shared/game-ui';

export const game: GameModule = {
  meta: { slug: 'stack', title: 'Perfect Stack', category: 'arcade', description: 'Catch a moving neon slab exactly over your tower.', instructions: 'Tap or press Space to drop each moving block.', accent: '#FF9F6E', mechanic: 'Time precise overlaps' },
  mount(host, services) {
    const frame = makeFrame(host, '#FF9F6E', 'Perfect Stack'); const { ctx, canvas } = frame; let base = { x: 180, w: 240 }, moving = { x: 0, w: 240 }, landed: Array<{ x: number; w: number }> = [], dir = 1, level = 0, score = 0, over = false, paused = false, raf = 0, last = 0;
    const draw = () => { ctx.fillStyle = '#101021'; ctx.fillRect(0, 0, 600, 600); landed.forEach((b, i) => { const y = 550 - i * 35; ctx.fillStyle = `hsl(${20 + i * 9}, 82%, ${60 - Math.min(i, 20)}%)`; ctx.fillRect(b.x, y, b.w, 29); ctx.fillStyle = '#ffffff2b'; ctx.fillRect(b.x + 4, y + 4, Math.max(0, b.w - 8), 4); }); const movingY = 550 - landed.length * 35; ctx.fillStyle = '#FF9F6E'; ctx.fillRect(moving.x, movingY, moving.w, 29); ctx.fillStyle = '#ffffff2b'; ctx.fillRect(moving.x + 4, movingY + 4, Math.max(0, moving.w - 8), 4); if (over) { ctx.fillStyle = '#F7F9FF'; ctx.font = '700 28px system-ui'; ctx.textAlign = 'center'; ctx.fillText(`TOWER ${level}`, 300, 260); ctx.font = '16px system-ui'; ctx.fillText('Press R to build again', 300, 294); ctx.textAlign = 'start'; } frame.setHud(`STACK ${level} · SCORE ${score} · BEST ${services.storage.get<number>('stack-best', 0)}`); };
    const reset = () => { base = { x: 180, w: 240 }; moving = { x: 0, w: 240 }; landed = [{ ...base }]; dir = 1; level = 0; score = 0; over = false; frame.setMessage('Land slabs precisely to grow higher.'); draw(); };
    const drop = () => { if (paused || over) return; const left = Math.max(base.x, moving.x), right = Math.min(base.x + base.w, moving.x + moving.w), overlap = right - left; if (overlap <= 1 || landed.length >= 15) { over = true; services.sound.play(overlap <= 1 ? 'fail' : 'success'); if (landed.length >= 15) services.reportComplete(1); services.storage.set('stack-best', Math.max(services.storage.get<number>('stack-best', 0), score)); frame.setMessage(overlap <= 1 ? 'The slab missed the tower.' : 'A 15-block skyline — perfect!'); draw(); return; } const perfect = Math.abs(base.x - moving.x) < 5 && Math.abs(base.w - moving.w) < 5; base = { x: left, w: overlap }; landed.push({ ...base }); level++; score += perfect ? 50 : Math.round(overlap / 4); services.reportScore(score); services.sound.play(perfect ? 'success' : 'tap'); moving = { x: dir > 0 ? 0 : 600 - base.w, w: base.w }; dir *= -1; frame.setMessage(perfect ? 'Perfect catch!' : 'Keep it centered.'); draw(); };
    const loop = (time: number) => { const elapsed = time - last; last = time; if (!paused && !over) { moving.x += dir * elapsed * (0.16 + level * .009); if (moving.x < 0 || moving.x + moving.w > 600) { moving.x = clamp(moving.x, 0, 600 - moving.w); dir *= -1; } draw(); } raf = requestAnimationFrame(loop); };
    frame.on(canvas, 'pointerup', (() => drop()) as EventListener); frame.on(frame.root, 'keydown', ((e: KeyboardEvent) => { if (e.key === ' ') { e.preventDefault(); drop(); } if (e.key.toLowerCase() === 'r') reset(); }) as EventListener);
    reset(); last = performance.now(); raf = requestAnimationFrame(loop); return { pause: () => { paused = true; }, resume: () => { paused = false; last = performance.now(); }, restart: reset, destroy: () => { cancelAnimationFrame(raf); frame.destroy(); } };
  },
};
export default game;
