import type { GameModule } from '../../core/game-types';
import { keyPrevent, makeFrame, xy } from '../_shared/game-ui';

const ANSWER = [5,3,4,6,7,8,9,1,2,6,7,2,1,9,5,3,4,8,1,9,8,3,4,2,5,6,7,8,5,9,7,6,1,4,2,3,4,2,6,8,5,3,7,9,1,7,1,3,9,2,4,8,5,6,9,6,1,5,3,7,2,8,4,2,8,7,4,1,9,6,3,5,3,4,5,2,8,6,1,7,9];
const GIVENS = new Set([0,1,4,9,12,13,14,19,20,25,27,30,31,35,36,39,40,41,44,45,49,53,54,58,60,61,66,67,68,71,76,77,80]);
export const game: GameModule = {
  meta: { slug: 'sudoku', title: 'Calm Sudoku', category: 'cards-logic', description: 'A quiet, focused number grid with gentle feedback.', instructions: 'Select a square, then tap a number or use your keyboard.', accent: '#70F0C2', mechanic: 'Fill a valid 9×9 grid' },
  mount(host, services) {
    const frame = makeFrame(host, '#70F0C2', 'Calm Sudoku'); const { ctx, canvas } = frame; let values: number[], selected = 2, paused = false, complete = false, errors = 0;
    const conflict = (i: number) => { const v = values[i]; if (!v) return false; const row = Math.floor(i / 9), col = i % 9, box = Math.floor(row / 3) * 3 + Math.floor(col / 3); return values.some((n, j) => j !== i && n === v && (Math.floor(j / 9) === row || j % 9 === col || (Math.floor(j / 9) * 3 + Math.floor(j % 9 / 3) === box))); };
    const draw = () => { ctx.fillStyle = '#0C1422'; ctx.fillRect(0, 0, 600, 600); const s = 54, ox = 57, oy = 14; for (let i = 0; i < 81; i++) { const x = ox + (i % 9) * s, y = oy + Math.floor(i / 9) * s; const same = values[i] && values[i] === values[selected]; ctx.fillStyle = i === selected ? '#70F0C238' : same ? '#70F0C212' : '#17243A'; ctx.fillRect(x + 1, y + 1, s - 2, s - 2); if (values[i]) { ctx.fillStyle = GIVENS.has(i) ? '#F7F9FF' : conflict(i) ? '#FF6B7A' : '#70F0C2'; ctx.font = `${GIVENS.has(i) ? '700' : '500'} 25px system-ui`; ctx.textAlign = 'center'; ctx.fillText(String(values[i]), x + s / 2, y + 35); } } ctx.strokeStyle = '#7f91ae'; for (let i = 0; i <= 9; i++) { ctx.lineWidth = i % 3 === 0 ? 3 : 1; ctx.beginPath(); ctx.moveTo(ox + i * s, oy); ctx.lineTo(ox + i * s, oy + 9 * s); ctx.stroke(); ctx.beginPath(); ctx.moveTo(ox, oy + i * s); ctx.lineTo(ox + 9 * s, oy + i * s); ctx.stroke(); }
      for (let n = 1; n <= 9; n++) { const x = 36 + (n - 1) * 59; ctx.fillStyle = '#253A50'; ctx.fillRect(x, 530, 52, 48); ctx.fillStyle = '#F7F9FF'; ctx.font = '700 21px system-ui'; ctx.textAlign = 'center'; ctx.fillText(String(n), x + 26, 562); } ctx.textAlign = 'start'; const progress = values.filter(Boolean).length - GIVENS.size; frame.setHud(`FILLED ${progress}/48 · ERRORS ${errors}`); };
    const set = (n: number) => { if (paused || complete || GIVENS.has(selected)) return; values[selected] = n; if (n && n !== ANSWER[selected]) { errors++; services.sound.play('fail'); } else services.sound.play('tap'); const filled = values.filter(Boolean).length - GIVENS.size; if (filled > services.storage.get<number>('sudoku-best', 0)) services.storage.set('sudoku-best', filled); if (values.every((v, i) => v === ANSWER[i])) { complete = true; services.sound.play('success'); services.reportComplete(1); frame.setMessage('Solved with a clear mind!'); } services.reportScore(filled * 10 - errors * 3); draw(); };
    const reset = () => { values = ANSWER.map((v, i) => GIVENS.has(i) ? v : 0); selected = 2; complete = false; errors = 0; frame.setMessage('One number at a time.'); draw(); };
    frame.on(canvas, 'pointerup', ((e: PointerEvent) => { const p = xy(canvas, e); if (p.y >= 530) { const n = Math.floor((p.x - 36) / 59) + 1; if (n >= 1 && n <= 9) set(n); return; } if (p.x >= 57 && p.x < 543 && p.y >= 14 && p.y < 500) { selected = Math.floor((p.y - 14) / 54) * 9 + Math.floor((p.x - 57) / 54); draw(); } }) as EventListener);
    frame.on(frame.root, 'keydown', ((e: KeyboardEvent) => { keyPrevent(e, ['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Backspace','Delete','r','R']); if (/^[1-9]$/.test(e.key)) set(Number(e.key)); if (e.key === 'Backspace' || e.key === 'Delete') set(0); if (e.key === 'ArrowUp') selected = Math.max(0, selected - 9); if (e.key === 'ArrowDown') selected = Math.min(80, selected + 9); if (e.key === 'ArrowLeft') selected = selected % 9 ? selected - 1 : selected; if (e.key === 'ArrowRight') selected = selected % 9 < 8 ? selected + 1 : selected; if (e.key.toLowerCase() === 'r') reset(); draw(); }) as EventListener);
    reset(); return { pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => frame.destroy() };
  },
};
export default game;
