import type { GameModule } from '../../core/game-types';
import { makeFrame, rr, xy } from '../_shared/game-ui';

const ICONS = ['✦','●','▲','◆','☾','✚','✿','♢']; const PALETTES = ['#70F0C2','#59C9FF','#FFDA74','#FF8195','#B18CFF','#FF9F6E','#8EE58C','#F7F9FF'];
export const game: GameModule = {
  meta: { slug: 'memory', title: 'Memory Flip', category: 'puzzle', description: 'Turn over starlit cards and find every twin.', instructions: 'Tap cards to reveal pairs. Match them all in as few turns as possible.', accent: '#59C9FF', mechanic: 'Match every pair' },
  mount(host, services) {
    const frame = makeFrame(host, '#59C9FF', 'Memory Flip'); const { ctx, canvas } = frame; let cards: number[] = [], open: number[] = [], matched = new Set<number>(), turns = 0, locked = false, paused = false, timer: number | undefined, cursor = 0;
    const reset = () => { cards = [...Array(8).keys(), ...Array(8).keys()]; for (let i = cards.length - 1; i; i--) { const j = rr(services, i + 1); [cards[i], cards[j]] = [cards[j], cards[i]]; } open = []; matched = new Set(); turns = 0; locked = false; if (timer) clearTimeout(timer); timer = undefined; cursor = 0; frame.setMessage('Remember the glow behind each card.'); draw(); };
    const draw = () => { ctx.fillStyle = '#0C1323'; ctx.fillRect(0, 0, 600, 600); cards.forEach((icon, i) => { const x = 54 + (i % 4) * 126, y = 70 + Math.floor(i / 4) * 126, face = open.includes(i) || matched.has(i); ctx.fillStyle = face ? '#F7F9FF' : '#273A5C'; ctx.fillRect(x, y, 108, 108); ctx.strokeStyle = i === cursor ? '#70F0C2' : face ? PALETTES[icon] : '#59C9FF66'; ctx.lineWidth = 3; ctx.strokeRect(x + 2, y + 2, 104, 104); ctx.fillStyle = face ? PALETTES[icon] : '#59C9FF'; ctx.font = '54px system-ui'; ctx.textAlign = 'center'; ctx.fillText(face ? ICONS[icon] : '✦', x + 54, y + 72); }); ctx.textAlign = 'start'; frame.setHud(`PAIRS ${matched.size / 2}/8 · TURNS ${turns}`); };
    const hideMismatch = () => { timer = window.setTimeout(() => { if (paused) { timer = undefined; return; } open = []; locked = false; timer = undefined; draw(); }, services.isReducedMotion ? 120 : 650); };
    const flip = (i: number) => { if (paused || locked || matched.has(i) || open.includes(i)) return; open.push(i); services.sound.play('tap'); if (open.length === 2) { turns++; if (cards[open[0]] === cards[open[1]]) { matched.add(open[0]); matched.add(open[1]); open = []; services.sound.play('success'); const result = Math.max(0, 1000 - turns * 30); services.reportScore(result); if (matched.size === cards.length) { services.storage.set('memory-best', Math.max(services.storage.get<number>('memory-best', 0), result)); services.reportComplete(1); frame.setMessage(`All pairs found in ${turns} turns!`); } } else { locked = true; hideMismatch(); services.sound.play('fail'); } } draw(); };
    frame.on(canvas, 'pointerup', ((e: PointerEvent) => { const p = xy(canvas, e), col = Math.floor((p.x - 54) / 126), row = Math.floor((p.y - 70) / 126); if (col >= 0 && col < 4 && row >= 0 && row < 4) { cursor = row * 4 + col; flip(cursor); } }) as EventListener); frame.on(frame.root, 'keydown', ((e: KeyboardEvent) => { if (e.key === 'ArrowLeft') cursor = cursor % 4 ? cursor - 1 : cursor; if (e.key === 'ArrowRight') cursor = cursor % 4 < 3 ? cursor + 1 : cursor; if (e.key === 'ArrowUp') cursor = Math.max(0, cursor - 4); if (e.key === 'ArrowDown') cursor = Math.min(15, cursor + 4); if (e.key === 'Enter' || e.key === ' ') flip(cursor); if (e.key.toLowerCase() === 'r') reset(); draw(); }) as EventListener);
    reset(); return { pause: () => { paused = true; if (timer) { clearTimeout(timer); timer = undefined; } }, resume: () => { paused = false; if (locked && !timer) hideMismatch(); }, restart: reset, destroy: () => { if (timer) clearTimeout(timer); frame.destroy(); } };
  },
};
export default game;
