import type { GameController, GameModule, GameServices } from '../../core/game-types';
import { clamp, makeKit, text } from '../arcade-kit';

export const invaders: GameModule = {
  meta: { slug:'invaders',title:'Pixel Defense',category:'action',description:'Defend the signal beacon from advancing pixel swarms.',instructions:'Move with arrows or drag; tap or Space fires.',accent:'#8b7cff',mechanic:'Shoot waves and dodge fire' },
  mount(host:HTMLElement, services:GameServices):GameController { const k=makeKit(host,services,'invaders');let raf=0,paused=false,over=false,score=0,wave=1,ship=160,dir=1,shot:{x:number;y:number}[]=[] ,enemyShot:{x:number;y:number}[]=[];let foes:{x:number;y:number;alive:boolean}[]=[];
    const reset=()=>{score=0;wave=1;over=false;ship=160;shot=[];enemyShot=[];spawn();}; const spawn=()=>{foes=[];for(let r=0;r<4;r++)for(let c=0;c<7;c++)foes.push({x:44+c*42,y:75+r*32,alive:true});}; reset();
    const fire=()=>{if(!over&&shot.length<3){shot.push({x:ship+20,y:470});services.sound.play('tap');}}; k.on('pointermove',e=>ship=clamp(k.point(e as PointerEvent).x-20,8,312));k.on('pointerdown',fire);k.on('keydown',e=>{if((e as KeyboardEvent).key===' ') {if(over)reset();else fire();}});
    const draw=()=>{const c=k.ctx;k.clear();c.fillStyle='#090d18';c.fillRect(0,0,360,560);text(c,`SCORE ${score}  WAVE ${wave}`,180,28,15,'#a8b1c5');c.fillStyle='#70f0c2';c.fillRect(ship,492,40,12);c.fillRect(ship+15,484,10,8);foes.filter(f=>f.alive).forEach(f=>{c.fillStyle='#8b7cff';c.fillRect(f.x,f.y,24,16);c.fillStyle='#f7f9ff';c.fillRect(f.x+4,f.y+4,4,4);c.fillRect(f.x+16,f.y+4,4,4);});c.fillStyle='#70f0c2';shot.forEach(s=>c.fillRect(s.x, s.y,3,12));c.fillStyle='#ff6b7a';enemyShot.forEach(s=>c.fillRect(s.x,s.y,3,10));if(paused)text(c,'PAUSED',180,280,27);if(over){text(c,'BEACON DOWN',180,260,25,'#ff6b7a');text(c,'Tap or Space to retry',180,290,15);}};
    let frames=0; const loop=()=>{if(!paused&&!over){frames++;if(k.keys.has('ArrowLeft')||k.keys.has('a'))ship=clamp(ship-5,8,312);if(k.keys.has('ArrowRight')||k.keys.has('d'))ship=clamp(ship+5,8,312);if(frames%(20-wave)>0){}else{let edge=false;foes.filter(f=>f.alive).forEach(f=>{f.x+=dir*(1+wave*.12);if(f.x<8||f.x>328)edge=true;});if(edge){dir*=-1;foes.forEach(f=>f.y+=12);}const live=foes.filter(f=>f.alive);if(live.length) {const f=live[Math.floor(services.random()*live.length)];enemyShot.push({x:f.x+12,y:f.y+16});}}
      shot.forEach(s=>s.y-=8);enemyShot.forEach(s=>s.y+=3+wave*.25);shot=shot.filter(s=>s.y>40);enemyShot=enemyShot.filter(s=>s.y<520);for(const s of shot)for(const f of foes)if(f.alive&&s.x>f.x&&s.x<f.x+24&&s.y>f.y&&s.y<f.y+18){f.alive=false;s.y=-20;score+=10;k.score(score);services.sound.play('success');}if(enemyShot.some(s=>s.x>ship&&s.x<ship+40&&s.y>480)){over=true;services.sound.play('fail');}if(foes.some(f=>f.alive&&f.y>450)){over=true;services.sound.play('fail');}if(!foes.some(f=>f.alive)){wave++;score+=50;k.score(score);services.reportComplete(wave);spawn();}}
      draw();raf=requestAnimationFrame(loop);};loop();return{pause:()=>paused=true,resume:()=>paused=false,restart:reset,destroy:()=>{cancelAnimationFrame(raf);k.dispose();}}; }
}; export default invaders;
