import type { GameController, GameModule, GameServices } from '../../core/game-types';
import { clamp, makeKit, text } from '../arcade-kit';

type Foe = { x: number; y: number; alive: boolean };
type Shot = { x: number; y: number };

export const invaders: GameModule = { meta: { slug: 'invaders', title: 'Pixel Defense', category: 'action', description: 'Defend the signal beacon from advancing pixel swarms.', instructions: 'Move with arrows or drag; tap or Space fires.', accent: '#8b7cff', mechanic: 'Shoot waves and dodge fire' }, mount(host: HTMLElement, services: GameServices): GameController {
  const k = makeKit(host, services, 'invaders'); let raf = 0, paused = false, over = false, score = 0, wave = 1, ship = 160, direction = 1, frames = 0;
  let shots: Shot[] = [], enemyShots: Shot[] = [], foes: Foe[] = [];
  const spawn = () => { foes = []; for (let row = 0; row < 4; row++) for (let col = 0; col < 7; col++) foes.push({ x: 44 + col * 42, y: 75 + row * 32, alive: true }); };
  const reset = () => { paused = false; over = false; score = 0; wave = 1; ship = 160; shots = []; enemyShots = []; k.fx.clear(); spawn(); }; reset();
  const fire = () => { if (!over && shots.length < 3) { shots.push({ x: ship + 20, y: 470 }); k.fx.burst(ship + 20, 482, '#70f0c2', 4); services.sound.play('shoot'); } }; k.on('pointermove', event => { ship = clamp(k.point(event as PointerEvent).x - 20, 8, 312); }); k.on('pointerdown', fire); k.on('keydown', event => { if ((event as KeyboardEvent).key === ' ') over ? reset() : fire(); });
  const draw = () => { const c = k.ctx; k.clear(); c.fillStyle = '#090d18'; c.fillRect(0, 0, 360, 560); text(c, `SCORE ${score}  WAVE ${wave}`, 180, 28, 15, '#a8b1c5'); c.fillStyle = '#70f0c2'; c.fillRect(ship, 492, 40, 12); c.fillRect(ship + 15, 484, 10, 8); foes.filter(foe => foe.alive).forEach(foe => { c.fillStyle = '#8b7cff'; c.fillRect(foe.x, foe.y, 24, 16); c.fillStyle = '#f7f9ff'; c.fillRect(foe.x + 4, foe.y + 4, 4, 4); c.fillRect(foe.x + 16, foe.y + 4, 4, 4); }); c.fillStyle = '#70f0c2'; shots.forEach(shot => c.fillRect(shot.x, shot.y, 3, 12)); c.fillStyle = '#ff6b7a'; enemyShots.forEach(shot => c.fillRect(shot.x, shot.y, 3, 10)); k.fx.draw(); if (paused) text(c, 'PAUSED', 180, 280, 27); if (over) { text(c, 'BEACON DOWN', 180, 260, 25, '#ff6b7a'); text(c, 'Tap or Space to retry', 180, 290, 15); } };
  const loop = () => { if (!paused && !over) { frames++; if (k.keys.has('ArrowLeft') || k.keys.has('a')) ship = clamp(ship - 5, 8, 312); if (k.keys.has('ArrowRight') || k.keys.has('d')) ship = clamp(ship + 5, 8, 312); const cadence = Math.max(5, 20 - wave); if (frames % cadence === 0) { let edge = false; foes.filter(foe => foe.alive).forEach(foe => { foe.x += direction * (1 + wave * .12); if (foe.x < 8 || foe.x > 328) edge = true; }); if (edge) { direction *= -1; foes.forEach(foe => { foe.y += 12; }); } const live = foes.filter(foe => foe.alive); if (live.length) { const foe = live[Math.floor(services.random() * live.length)]; enemyShots.push({ x: foe.x + 12, y: foe.y + 16 }); } }
    shots.forEach(shot => { shot.y -= 8; }); enemyShots.forEach(shot => { shot.y += 3 + wave * .25; }); shots = shots.filter(shot => shot.y > 40); enemyShots = enemyShots.filter(shot => shot.y < 520); for (const shot of shots) for (const foe of foes) if (foe.alive && shot.x > foe.x && shot.x < foe.x + 24 && shot.y > foe.y && shot.y < foe.y + 18) { foe.alive = false; shot.y = -20; score += 10; k.score(score); k.fx.burst(foe.x + 12, foe.y + 8, '#ff6b7a'); services.sound.play('hit'); }
    if (enemyShots.some(shot => shot.x > ship && shot.x < ship + 40 && shot.y > 480) || foes.some(foe => foe.alive && foe.y > 450)) { over = true; k.fx.flash('#ff6b7a'); services.sound.play('fail'); } if (!foes.some(foe => foe.alive)) { wave++; score += 50; k.score(score); services.reportComplete(wave); spawn(); k.fx.flash('#8b7cff'); services.sound.play('clear'); } k.fx.step(); } draw(); raf = requestAnimationFrame(loop); };
  loop(); return { pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => { cancelAnimationFrame(raf); k.dispose(); } };
} };
export default invaders;
