import type { GameModule } from '../../core/game-types';
import { makeFrame, rr, xy } from '../_shared/game-ui';

type Card = { suit: number; rank: number; up: boolean }; type Pick = { pile: number; index: number } | { pile: -1; index: 0 };
const suits = ['♠', '♥', '♦', '♣']; const color = (c: Card) => c.suit === 1 || c.suit === 2;
export const game: GameModule = {
  meta: { slug: 'solitaire', title: 'Daily Solitaire', category: 'cards-logic', description: 'A calm original Klondike table with midnight cards.', instructions: 'Tap a face-up card, then a destination column or foundation.', accent: '#FFDA74', mechanic: 'Sort cards into foundations' },
  mount(host, services) {
    const frame = makeFrame(host, '#FFDA74', 'Daily Solitaire'); const { ctx, canvas } = frame; let stock: Card[], waste: Card[], tabs: Card[][], foundations: Card[][], selected: Pick | null = null, score = 0, paused = false;
    const deck = () => { const d: Card[] = []; for (let s = 0; s < 4; s++) for (let r = 1; r <= 13; r++) d.push({ suit: s, rank: r, up: false }); for (let i = d.length - 1; i; i--) { const j = rr(services, i + 1); [d[i], d[j]] = [d[j], d[i]]; } return d; };
    const label = (c: Card) => `${c.rank === 1 ? 'A' : c.rank === 11 ? 'J' : c.rank === 12 ? 'Q' : c.rank === 13 ? 'K' : c.rank}${suits[c.suit]}`;
    const source = () => selected?.pile === -1 ? waste : selected ? tabs[selected.pile].slice(selected.index) : [];
    const reset = () => { const d = deck(); tabs = Array.from({ length: 7 }, (_, i) => d.splice(0, i + 1)); tabs.forEach(p => p[p.length - 1].up = true); stock = d; waste = []; foundations = [[], [], [], []]; selected = null; score = 0; frame.setMessage('Build down in alternating colors; send aces home.'); draw(); };
    const drawCard = (x: number, y: number, c?: Card, back = false, selectedCard = false) => { ctx.fillStyle = c && !back ? '#F7F9FF' : '#253451'; ctx.fillRect(x, y, 70, 96); ctx.strokeStyle = selectedCard ? '#70F0C2' : '#5C6C90'; ctx.lineWidth = selectedCard ? 3 : 1; ctx.strokeRect(x + 1, y + 1, 68, 94); if (c && !back) { ctx.fillStyle = color(c) ? '#E85C72' : '#18233A'; ctx.font = '700 17px system-ui'; ctx.fillText(label(c), x + 7, y + 22); ctx.font = '30px system-ui'; ctx.fillText(suits[c.suit], x + 23, y + 66); } else if (back) { ctx.fillStyle = '#8B7CFF'; for (let i = 8; i < 64; i += 12) ctx.fillRect(x + i, y + 10, 5, 76); } };
    const draw = () => { ctx.fillStyle = '#0A1321'; ctx.fillRect(0, 0, 600, 600); drawCard(22, 20, stock[stock.length - 1], stock.length > 0); drawCard(112, 20, waste[waste.length - 1]); foundations.forEach((p, i) => { const x = 290 + i * 76; drawCard(x, 20, p[p.length - 1]); if (!p.length) { ctx.strokeStyle = '#ffffff24'; ctx.strokeRect(x + 1, 21, 68, 94); ctx.fillStyle = '#A8B1C5'; ctx.font = '20px system-ui'; ctx.fillText(suits[i], x + 25, 77); } }); tabs.forEach((pile, col) => pile.forEach((card, i) => drawCard(22 + col * 82, 142 + i * 28, card, !card.up, selected?.pile === col && selected.index === i))); frame.setHud(`SCORE ${score} · HOME ${foundations.reduce((n, p) => n + p.length, 0)}/52`); };
    const selectable = (p: Pick) => { const cards = p.pile === -1 ? waste : tabs[p.pile].slice(p.index); return cards.length && cards[0].up; };
    const pick = (p: Pick) => { if (selectable(p)) { selected = p; services.sound.play('tap'); draw(); } };
    const expose = (col: number) => { const top = tabs[col].at(-1); if (top && !top.up) { top.up = true; score += 5; } };
    const report = () => { services.reportScore(score); if (score > services.storage.get<number>('solitaire-best', 0)) services.storage.set('solitaire-best', score); };
    const toFoundation = () => { const cards = source(); if (cards.length !== 1) return false; const c = cards[0], foundation = foundations[c.suit]; if (c.rank !== foundation.length + 1) return false; const from = selected!.pile; if (from === -1) waste.pop(); else tabs[from].splice(selected!.index); foundation.push(c); score += 10; if (from >= 0) expose(from); selected = null; services.sound.play('upgrade'); report(); if (foundations.every(p => p.length === 13)) { services.reportComplete(1); services.sound.play('success'); frame.setMessage('All suits are home — a perfect table!'); } return true; };
    const toTableau = (col: number) => { if (!selected || selected.pile === col) return false; const moving = source(), target = tabs[col].at(-1); if (!moving.length || (target ? (!target.up || target.rank !== moving[0].rank + 1 || color(target) === color(moving[0])) : moving[0].rank !== 13)) return false; if (selected.pile === -1) waste.pop(); else tabs[selected.pile].splice(selected.index); tabs[col].push(...moving); if (selected.pile >= 0) expose(selected.pile); selected = null; score += 5; services.sound.play('move'); report(); return true; };
    const click = (p: { x: number; y: number }) => { if (paused) return; if (p.y < 120) { if (p.x < 95) { if (stock.length) { const c = stock.pop()!; c.up = true; waste.push(c); services.sound.play('tap'); } else { stock = waste.reverse().map(c => ({ ...c, up: false })); waste = []; } selected = null; draw(); return; } if (p.x >= 112 && p.x < 190) { if (selected) { if (!toFoundation()) pick({ pile: -1, index: 0 }); } else pick({ pile: -1, index: 0 }); draw(); return; } const f = Math.floor((p.x - 290) / 76); if (f >= 0 && f < 4 && selected) { toFoundation(); draw(); return; } }
      if (p.y >= 142) { const col = Math.floor((p.x - 22) / 82); if (col < 0 || col > 6) return; const pile = tabs[col]; const index = Math.min(pile.length - 1, Math.floor((p.y - 142) / 28)); if (selected && toTableau(col)) { draw(); return; } if (index >= 0) pick({ pile: col, index }); draw(); }
    };
    frame.on(canvas, 'pointerup', ((e: PointerEvent) => click(xy(canvas, e))) as EventListener); frame.on(frame.root, 'keydown', ((e: KeyboardEvent) => { if (e.key.toLowerCase() === 'r') reset(); if (e.key.toLowerCase() === 'd') click({ x: 45, y: 50 }); if (e.key.toLowerCase() === 'w') click({ x: 145, y: 50 }); if (e.key.toLowerCase() === 'f' || e.key === 'Enter') { if (selected) toFoundation(); draw(); } if (/^[1-7]$/.test(e.key)) { const col = Number(e.key) - 1; if (!selected || !toTableau(col)) pick({ pile: col, index: Math.max(0, tabs[col].length - 1) }); draw(); } }) as EventListener);
    reset(); return { pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => frame.destroy() };
  },
};
export default game;
