import type { GameModule } from '../../core/game-types';
import { clamp, makeFrame } from '../_shared/game-ui';

type Pipe = { x: number; gap: number; scored: boolean };
export const game: GameModule = {
  meta: { slug: 'flap', title: 'Sky Flap', category: 'action', description: 'A tiny comet bird races through the twilight gates.', instructions: 'Tap the stage or press Space to flap through each gap.', accent: '#59C9FF', mechanic: 'Flap through moving gates' },
  mount(host, services) {
    const frame = makeFrame(host, '#59C9FF', 'Sky Flap'); const { ctx, canvas } = frame; let y = 300, vy = 0, pipes: Pipe[] = [], score = 0, ended = false, started = false, paused = false, raf = 0, last = 0;
    const reset = () => { y = 300; vy = 0; pipes = [{ x: 620, gap: 230, scored: false }, { x: 930, gap: 365, scored: false }]; score = 0; ended = false; started = false; frame.setMessage('Tap once to launch, then keep your comet aloft.'); draw(); };
    const draw = () => { const gradient = ctx.createLinearGradient(0, 0, 0, 600); gradient.addColorStop(0, '#17244B'); gradient.addColorStop(1, '#0B1021'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, 600, 600); ctx.fillStyle = '#ffffff55'; for (let i = 0; i < 35; i++) ctx.fillRect((i * 83) % 600, (i * 47) % 420, 2, 2); pipes.forEach(pipe => { const gapH = Math.max(116, 164 - score * 2), top = pipe.gap - gapH / 2, bottom = pipe.gap + gapH / 2; ctx.fillStyle = '#70F0C2'; ctx.fillRect(pipe.x, 0, 74, top); ctx.fillRect(pipe.x, bottom, 74, 600 - bottom); ctx.fillStyle = '#b9ffe7'; ctx.fillRect(pipe.x - 5, top - 12, 84, 12); ctx.fillRect(pipe.x - 5, bottom, 84, 12); }); ctx.save(); ctx.translate(170, y); ctx.rotate(clamp(vy / 900, -.45, .8)); ctx.fillStyle = '#FFDA74'; ctx.beginPath(); ctx.arc(0, 0, 18, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#F7F9FF'; ctx.beginPath(); ctx.moveTo(-8, 5); ctx.lineTo(-34, 16); ctx.lineTo(-15, -6); ctx.fill(); ctx.fillStyle = '#17244B'; ctx.fillRect(7, -7, 5, 5); ctx.restore(); if (!started && !ended) { ctx.fillStyle = '#F7F9FF'; ctx.font = '700 22px system-ui'; ctx.textAlign = 'center'; ctx.fillText('TAP TO FLY', 300, 110); ctx.textAlign = 'start'; } if (ended) { ctx.fillStyle = '#F7F9FF'; ctx.font = '700 26px system-ui'; ctx.textAlign = 'center'; ctx.fillText(`FLIGHT OVER · ${score}`, 300, 260); ctx.font = '15px system-ui'; ctx.fillText('Press R to restart', 300, 290); ctx.textAlign = 'start'; } frame.setHud(`GATES ${score} · BEST ${services.storage.get<number>('flap-best', 0)}`); };
    const flap = () => { if (paused) return; if (ended) { reset(); return; } started = true; vy = -380; services.sound.play('move'); draw(); };
    const end = () => { ended = true; const record = Math.max(services.storage.get<number>('flap-best', 0), score); services.storage.set('flap-best', record); services.reportScore(score); services.sound.play('fail'); frame.setMessage(`You cleared ${score} gate${score === 1 ? '' : 's'}.`); };
    const loop = (time: number) => { let dt = Math.min(.035, (time - last) / 1000); last = time; if (started && !paused && !ended) { vy += 880 * dt; y += vy * dt; pipes.forEach(p => { p.x -= (145 + score * 5) * dt; if (!p.scored && p.x + 74 < 170) { p.scored = true; score++; services.reportScore(score); services.sound.play('success'); } }); const tail = pipes.at(-1)!; if (pipes[0].x < -90) pipes.shift(); if (tail.x < 350) pipes.push({ x: tail.x + 310, gap: 145 + services.random() * 310, scored: false }); const hit = y - 17 < 0 || y + 17 > 600 || pipes.some(p => 170 + 16 > p.x && 170 - 16 < p.x + 74 && (y - 14 < p.gap - Math.max(116, 164 - score * 2) / 2 || y + 14 > p.gap + Math.max(116, 164 - score * 2) / 2)); if (hit) end(); draw(); } raf = requestAnimationFrame(loop); };
    frame.on(canvas, 'pointerup', (() => flap()) as EventListener); frame.on(frame.root, 'keydown', ((e: KeyboardEvent) => { if (e.key === ' ') { e.preventDefault(); flap(); } if (e.key.toLowerCase() === 'r') reset(); }) as EventListener);
    reset(); last = performance.now(); raf = requestAnimationFrame(loop); return { pause: () => { paused = true; }, resume: () => { paused = false; last = performance.now(); }, restart: reset, destroy: () => { cancelAnimationFrame(raf); frame.destroy(); } };
  },
};
export default game;
