export type MobileControlShape = 'dpad' | 'horizontal' | 'single-action' | 'dual-action' | 'stick-action';
export type MobileControls = { clear(): void; destroy(): void };
export type MobileControlOptions = { shape: MobileControlShape; labels?: readonly string[]; onChange(action: string, held: boolean): void; pause?: boolean };
export const continuousSlugs = ['block-drop', 'snake', 'stack', 'flap', 'breakout', 'invaders', 'runner', 'platformer', 'drive', 'fruit-merge', 'bubble', 'knife', 'arena'] as const;
export const mobileProfiles: Record<string, { shape: MobileControlShape; labels: readonly string[] }> = {
  'block-drop': { shape: 'dpad', labels: ['Up', 'Left', 'Down', 'Right', 'Rotate', 'Drop'] }, snake: { shape: 'dpad', labels: ['Up', 'Left', 'Down', 'Right'] }, stack: { shape: 'single-action', labels: ['Drop'] }, flap: { shape: 'single-action', labels: ['Flap'] },
  breakout: { shape: 'horizontal', labels: ['Left', 'Right'] }, invaders: { shape: 'dual-action', labels: ['Left', 'Right', 'Fire'] }, runner: { shape: 'dpad', labels: ['Up', 'Left', 'Down', 'Right'] }, platformer: { shape: 'dual-action', labels: ['Left', 'Right', 'Jump'] }, drive: { shape: 'dual-action', labels: ['Brake', 'Drive'] }, 'fruit-merge': { shape: 'dual-action', labels: ['Left', 'Right', 'Drop'] }, bubble: { shape: 'dual-action', labels: ['Left', 'Right', 'Shoot'] }, knife: { shape: 'single-action', labels: ['Throw'] }, arena: { shape: 'stick-action', labels: ['Attack'] }
};

const shouldRender = () => globalThis.matchMedia?.('(pointer: coarse)').matches || globalThis.matchMedia?.('(max-width: 720px)').matches;
const defaultLabels: Record<MobileControlShape, readonly string[]> = { dpad: ['Up', 'Left', 'Down', 'Right'], horizontal: ['Left', 'Right'], 'single-action': ['Action'], 'dual-action': ['Left action', 'Right action'], 'stick-action': ['Move', 'Action'] };

/** Owned, pointer-capture controls for every mobile cabinet. */
export function createMobileControls(host: HTMLElement, options: MobileControlOptions): MobileControls {
  if (!shouldRender()) return { clear() {}, destroy() {} };
  const root = document.createElement('div'); root.className = `mobile-controls mobile-controls--${options.shape}`; root.setAttribute('aria-label', 'Touch controls');
  const held = new Map<number, string>(); const labels = options.labels ?? defaultLabels[options.shape]; const buttons = new Map<string, HTMLButtonElement>(); let releaseStick = () => undefined;
  const release = (pointer?: number) => { const releasing = [...held].filter(([id]) => pointer === undefined || id === pointer); const actions = new Set(releasing.map(([, action]) => action)); releasing.forEach(([id]) => held.delete(id)); actions.forEach((action) => { if (![...held.values()].includes(action)) { buttons.get(action)?.classList.remove('is-held'); options.onChange(action, false); } }); };
  const press = (action: string, event: PointerEvent, button: HTMLButtonElement) => { event.preventDefault(); button.setPointerCapture?.(event.pointerId); const wasHeld = [...held.values()].includes(action); held.set(event.pointerId, action); button.classList.add('is-held'); if (!wasHeld) options.onChange(action, true); navigator.vibrate?.(8); };
  if (options.shape === 'stick-action') { const stick = document.createElement('div'); stick.className = 'mobile-stick'; stick.setAttribute('role', 'application'); stick.setAttribute('aria-label', 'Virtual movement stick'); const knob = document.createElement('span'); stick.append(knob); let direction = ''; const update = (event: PointerEvent) => { const box = stick.getBoundingClientRect(), dx = event.clientX - (box.left + box.width / 2), dy = event.clientY - (box.top + box.height / 2), length = Math.hypot(dx, dy), deadzone = Math.min(box.width, box.height) * .18; const next = length < deadzone ? '' : Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? 'right' : 'left') : (dy > 0 ? 'down' : 'up'); if (next !== direction) { if (direction) options.onChange(direction, false); direction = next; if (direction) options.onChange(direction, true); } const capped = Math.min(length, box.width * .34), scale = length ? capped / length : 0; knob.style.transform = `translate(${dx * scale}px,${dy * scale}px)`; }; stick.addEventListener('pointerdown', (event) => { event.preventDefault(); stick.setPointerCapture?.(event.pointerId); update(event); }); stick.addEventListener('pointermove', (event) => { if (stick.hasPointerCapture?.(event.pointerId)) update(event); }); releaseStick = () => { if (direction) options.onChange(direction, false); direction = ''; knob.style.transform = ''; }; stick.addEventListener('pointerup', releaseStick); stick.addEventListener('pointercancel', releaseStick); root.append(stick); }
  labels.forEach((label) => { const button = document.createElement('button'); const action = label.toLowerCase().replaceAll(' ', '-'); button.type = 'button'; button.className = 'mobile-control'; button.textContent = label; button.setAttribute('aria-label', label); buttons.set(action, button); button.addEventListener('pointerdown', (event) => press(action, event, button)); button.addEventListener('pointerup', (event) => release(event.pointerId)); button.addEventListener('pointercancel', (event) => release(event.pointerId)); root.append(button); });
  if (options.pause) { const pause = document.createElement('button'); pause.type = 'button'; pause.className = 'stage-pause'; pause.textContent = 'Ⅱ'; pause.setAttribute('aria-label', 'Pause game'); pause.addEventListener('click', () => host.dispatchEvent(new CustomEvent('integ:pause-request', { bubbles: true }))); root.append(pause); }
  const clear = () => { release(); releaseStick(); }; const abort = new AbortController(); window.addEventListener('blur', clear, { signal: abort.signal }); document.addEventListener('visibilitychange', () => { if (document.hidden) clear(); }, { signal: abort.signal }); host.addEventListener('integ:clear-controls', clear, { signal: abort.signal }); host.append(root);
  return { clear, destroy() { clear(); abort.abort(); root.remove(); } };
}

export function attachKeyboardMobileControls(host: HTMLElement, slug: string, target: HTMLElement): MobileControls | undefined {
  const profile = mobileProfiles[slug];
  if (!profile) return undefined;
  const keyFor: Record<string, string> = { up: 'ArrowUp', down: 'ArrowDown', left: 'ArrowLeft', right: 'ArrowRight', rotate: 'ArrowUp', drop: ' ', flap: ' ', throw: ' ', fire: ' ', jump: 'ArrowUp', brake: 'ArrowLeft', drive: 'ArrowRight', shoot: ' ', attack: ' ' };
  return createMobileControls(host, { ...profile, pause: continuousSlugs.includes(slug as typeof continuousSlugs[number]), onChange: (action, held) => target.dispatchEvent(new KeyboardEvent(held ? 'keydown' : 'keyup', { key: keyFor[action] ?? ' ', bubbles: true })) });
}
